{
  "hash": "b6d21adc549b8033e1ac4d81f52b1818",
  "result": {
    "markdown": "---\ntitle: \"Chapter 3: HRMPA\"\nauthor: \"Robert W. Walker\"\ndate: \"2022-09-28\"\ncategories: [news]\n---\n\n\n\n\n## 3.6.2 Data exercises\n\nFor these exercises, load the `charity_donation` data set via the `peopleanalyticsdata` package, or download it from the internet. *This data set contains information on a sample of individuals who made donations to a nature charity.*\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse); library(magrittr)\ncharity_data <- read.csv(\"http://peopleanalytics-regression-book.org/data/charity_donation.csv\")\n```\n:::\n\n\n1. Calculate the mean `total_donations` from the data set.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(charity_data$total_donations)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2350.141\n```\n:::\n\n```{.r .cell-code}\ncharity_data$total_donations %>% mean\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2350.141\n```\n:::\n:::\n\n**The mean of `total_donations` is 2350.14.**\n\n2. Calculate the sample variance for `total_donations` and convert this to a population variance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Sample variance\nvar(charity_data$total_donations)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 6232905\n```\n:::\n\n```{.r .cell-code}\n# Population variance\n((length(charity_data$total_donations)-1)/length(charity_data$total_donations))*var(charity_data$total_donations)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 6215297\n```\n:::\n:::\n\n**The sample variance for `total_donations` is 6232904.5125718 while the population variance is slightly smaller: 6215297.4376776.**\n\n3. Calculate the sample standard deviation for `total_donations` and verify that it is the same as the square root of the sample variance.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsd(charity_data$total_donations)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2496.579\n```\n:::\n\n```{.r .cell-code}\nsd(charity_data$total_donations)==sqrt(var(charity_data$total_donations))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] TRUE\n```\n:::\n:::\n\n\n\n4. Calculate the sample correlation between `total_donations` and `time_donating`. By using an appropriate hypothesis test, determine if these two variables are independent in the overall population.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncor.test(charity_data$total_donations, charity_data$time_donating)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  charity_data$total_donations and charity_data$time_donating\nt = 14.69, df = 352, p-value < 2.2e-16\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.5474266 0.6772030\nsample estimates:\n      cor \n0.6164845 \n```\n:::\n\n```{.r .cell-code}\ncharity_data %$% cor.test(total_donations, time_donating)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  total_donations and time_donating\nt = 14.69, df = 352, p-value < 2.2e-16\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.5474266 0.6772030\nsample estimates:\n      cor \n0.6164845 \n```\n:::\n:::\n\n**These two variables are quite unlikely to be independent in the population.  The correlation is 0.616 and, with 95% confidence, ranges from 0.55 to 0.68.  There is basically zero probability of finding a correlation that high by chance alone.**\n\n5. Calculate the mean and the standard error of the mean for the first 20 entries of `total_donations`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(charity_data$total_donations[1:20])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1851\n```\n:::\n\n```{.r .cell-code}\nsd(charity_data$total_donations[1:20])/sqrt(length(charity_data$total_donations[1:20]))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 315.0922\n```\n:::\n:::\n\n\n6. Calculate the mean and the standard error of the mean for the first 50 entries of `total_donations`. Verify that the standard error is less than in Exercise 5.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmean(charity_data$total_donations[1:50])\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2026.4\n```\n:::\n\n```{.r .cell-code}\nsd(charity_data$total_donations[1:50])/sqrt(length(charity_data$total_donations[1:50]))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 240.7464\n```\n:::\n:::\n\n\n**The standard error of the first 50 is 240.7 while the standard error of the first 20 is 315.1.  Verified.**\n\n7. By using an appropriate hypothesis test, determine if the mean age of those who made a recent donation is different from those who did not.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt.test(age~recent_donation, data=charity_data)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  age by recent_donation\nt = -10.207, df = 105.15, p-value < 2.2e-16\nalternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0\n95 percent confidence interval:\n -24.47608 -16.51365\nsample estimates:\nmean in group 0 mean in group 1 \n       42.19188        62.68675 \n```\n:::\n\n```{.r .cell-code}\ncharity_data %>% t.test(age~recent_donation, data=.)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  age by recent_donation\nt = -10.207, df = 105.15, p-value < 2.2e-16\nalternative hypothesis: true difference in means between group 0 and group 1 is not equal to 0\n95 percent confidence interval:\n -24.47608 -16.51365\nsample estimates:\nmean in group 0 mean in group 1 \n       42.19188        62.68675 \n```\n:::\n:::\n\n**The age of recent donors is between 16.5 and 24.5 years higher than those of non-recent donors with 95% confidence.  The probability that such a large difference would be observed by random chance if there was no difference is basically zero.**\n\n8. By using an appropriate hypothesis test, determine if there is a difference in whether or not a recent donation was made according to where people reside.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchisq.test(charity_data$recent_donation, charity_data$reside)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's Chi-squared test\n\ndata:  charity_data$recent_donation and charity_data$reside\nX-squared = 16.176, df = 2, p-value = 0.0003072\n```\n:::\n:::\n\n\n**Both variables are categorical, this a chi-square test of independence is indicated.  The evidence suggests that likelihood of recent donations depends on where an individual resides.**\n\nFor a bit of detail, I will deploy `janitor::tabyl`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(janitor)\ncharity_data %>% tabyl(reside, recent_donation) %>% adorn_percentages(\"row\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         reside         0         1\n       Overseas 0.8782609 0.1217391\n Rural Domestic 0.6616541 0.3383459\n Urban Domestic 0.7735849 0.2264151\n```\n:::\n:::\n\n\n9. **Extension**: By using an appropriate hypothesis test, determine if the age of those who have recently donated is at least 10 years older than those who have not recently donated in the population.\n\n**Yes.  This is fairly clear from the evidence in question 7.  Though more formally, as an hypothesis test, we should use evidence only in one tail.  It is worth noting that the first group [0] is smaller, so we really mean a difference less than -10 and the evidence suggests that this is true as it is very unlikely to have occurred by chance alone.**\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncharity_data %>% t.test(age~recent_donation, data=., alt=\"l\", mu=-10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  age by recent_donation\nt = -5.2268, df = 105.15, p-value = 0.0000004403\nalternative hypothesis: true difference in means between group 0 and group 1 is less than -10\n95 percent confidence interval:\n      -Inf -17.16282\nsample estimates:\nmean in group 0 mean in group 1 \n       42.19188        62.68675 \n```\n:::\n:::\n\n\n\n10. **Extension**: By using an appropriate hypothesis test, determine if the average donation amount is at least 10 dollars higher for those who recently donated versus those who did not. Retest for 20 dollars higher.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncharity_data %>% mutate(avg_donation = total_donations/n_donations) %>% t.test(avg_donation~recent_donation, data=., mu=-10, alt=\"l\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  avg_donation by recent_donation\nt = -2.5035, df = 179.45, p-value = 0.006595\nalternative hypothesis: true difference in means between group 0 and group 1 is less than -10\n95 percent confidence interval:\n     -Inf -19.2951\nsample estimates:\nmean in group 0 mean in group 1 \n       356.2168        393.5902 \n```\n:::\n\n```{.r .cell-code}\ncharity_data %>% mutate(avg_donation = total_donations/n_donations) %>% t.test(avg_donation~recent_donation, data=., mu=-20, alt=\"l\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  avg_donation by recent_donation\nt = -1.5889, df = 179.45, p-value = 0.05692\nalternative hypothesis: true difference in means between group 0 and group 1 is less than -20\n95 percent confidence interval:\n     -Inf -19.2951\nsample estimates:\nmean in group 0 mean in group 1 \n       356.2168        393.5902 \n```\n:::\n:::\n\n**It is at least 10 dollars higher with 95% confidence but it is not quite at least 20 dollars higher with 95% confidence.  In the former case, the probability of such a large difference by random chance is 0.007 while in the latter case, it is 0.06.**",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}